### ISSUE TITLE
Invalid statement: "return-void"

### ISSUE THREAD

**Issue by astrary** [MatrixEditor/pysmali#2]
using NamePrinterVisitor example with hardcoded fix for _handle_parameter

dex used: http://temp.sh/YBfst/dex_example.dex

```
Class: com.miui.hidden.PrivateApi
Traceback (most recent call last):
  File "-", line 20, in <module>
    reader.visit(__code__, NamePrinterVisitor())
  File "C:\Users\nighty\AppData\Local\Programs\Python\Python311\Lib\site-packages\smali\reader.py", line 159, in visit
    self._do_visit()
  File "C:\Users\nighty\AppData\Local\Programs\Python\Python311\Lib\site-packages\smali\reader.py", line 344, in _do_visit
    raise SyntaxError(f'Invalid statement: "{statement}"')
SyntaxError: Invalid statement: "return-void"
```

**Comment by MatrixEditor** [comment]
Both issues will be fixed with the next release. This one here results from improper parsing:
```python
        directive = self.line.last() # in SmaliReader._handle_end
```
In the decompiled Smali file we can see that the `.end` directive stores not two elements, but three. Using `.last()` leads to issues and therefore will be removed with the next push.

**Comment by astrary** [comment]
thats good
